#!/usr/bin/python -u

import sys, os
from MAPI import *
from MAPI.Util import *

PR_EC_OUTOFOFFICE                   = PROP_TAG(PT_BOOLEAN,    PR_EC_BASE+0x60)
PR_EC_OUTOFOFFICE_MSG               = PROP_TAG(PT_TSTRING,    PR_EC_BASE+0x61)
PR_EC_OUTOFOFFICE_SUBJECT           = PROP_TAG(PT_TSTRING,    PR_EC_BASE+0x62)

if len(sys.argv) < 3:
    print "Usage: %s <username> <0|1> [<oof_subject>] [</path/to/oof/message.txt>]" % sys.argv[0]
    exit(1)

def PrintSubject(subject):
    if subject.ulPropTag == PR_EC_OUTOFOFFICE_SUBJECT:
        print "Current subject: '%s'" % subject.Value
    else:
        print "No subject set"


enabled = bool(int(sys.argv[2]))

try:
    session = OpenECSession(sys.argv[1], '', os.getenv('ZARAFA_SOCKET','file:///var/run/zarafa'))
    st = GetDefaultStore(session)
except MAPIError, e:
    print "Unable to open store for user %s" % sys.argv[1]
    exit(1)

props = st.GetProps([PR_EC_OUTOFOFFICE, PR_EC_OUTOFOFFICE_SUBJECT], 0)
if props[0].ulPropTag == PR_EC_OUTOFOFFICE:
    if props[0].Value == True and enabled:
        print "Not changing subject and message for user %s which already has out of office message enbled." % sys.argv[1]
        PrintSubject(props[1])
        exit(0)
    elif not props[0].Value and not enabled:
        print "Out of office is already disabled for user %s" % sys.argv[1]
        exit(0)

st.SetProps([SPropValue(PR_EC_OUTOFOFFICE, enabled)])

if(enabled):
    if len(sys.argv) >= 4:
        st.SetProps([SPropValue(PR_EC_OUTOFOFFICE_SUBJECT, sys.argv[3])])

    if len(sys.argv) >= 5:
        f = open(sys.argv[4], 'rt')
        msg = f.read()
        st.SetProps([SPropValue(PR_EC_OUTOFOFFICE_MSG, msg)])
        f.close()

    print "Out of office enabled for user %s" % sys.argv[1]
    props = st.GetProps([PR_EC_OUTOFOFFICE_SUBJECT], 0)
    PrintSubject(props[0])
else:
    print "Out of office disabled for user %s" % sys.argv[1]
