# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.36
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _licenseclient
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class ECLicenseClient(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ECLicenseClient, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ECLicenseClient, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _licenseclient.new_ECLicenseClient(*args)
        try: self.this.append(this)
        except: self.this = this
    def GetCapabilities(*args): return _licenseclient.ECLicenseClient_GetCapabilities(*args)
    def GetSerial(*args): return _licenseclient.ECLicenseClient_GetSerial(*args)
    def GetInfo(*args): return _licenseclient.ECLicenseClient_GetInfo(*args)
    def SetSerial(*args): return _licenseclient.ECLicenseClient_SetSerial(*args)
    def Auth(*args): return _licenseclient.ECLicenseClient_Auth(*args)
    __swig_destroy__ = _licenseclient.delete_ECLicenseClient
    __del__ = lambda self : None;
ECLicenseClient_swigregister = _licenseclient.ECLicenseClient_swigregister
ECLicenseClient_swigregister(ECLicenseClient)



