# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_licenseclient', [dirname(__file__)])
        except ImportError:
            import _licenseclient
            return _licenseclient
        if fp is not None:
            try:
                _mod = imp.load_module('_licenseclient', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _licenseclient = swig_import_helper()
    del swig_import_helper
else:
    import _licenseclient
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class ECLicenseClient(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ECLicenseClient, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ECLicenseClient, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _licenseclient.new_ECLicenseClient(*args)
        try: self.this.append(this)
        except: self.this = this
    def GetCapabilities(self, *args): return _licenseclient.ECLicenseClient_GetCapabilities(self, *args)
    def GetSerial(self, *args): return _licenseclient.ECLicenseClient_GetSerial(self, *args)
    def GetInfo(self, *args): return _licenseclient.ECLicenseClient_GetInfo(self, *args)
    def SetSerial(self, *args): return _licenseclient.ECLicenseClient_SetSerial(self, *args)
    def Auth(self, *args): return _licenseclient.ECLicenseClient_Auth(self, *args)
    __swig_destroy__ = _licenseclient.delete_ECLicenseClient
    __del__ = lambda self : None;
ECLicenseClient_swigregister = _licenseclient.ECLicenseClient_swigregister
ECLicenseClient_swigregister(ECLicenseClient)



