/*
 * Copyright 2005 - 2015  Zarafa B.V. and its licensors
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation with the following
 * additional terms according to sec. 7:
 * 
 * "Zarafa" is a registered trademark of Zarafa B.V.
 * The licensing of the Program under the AGPL does not imply a trademark 
 * license. Therefore any rights, title and interest in our trademarks 
 * remain entirely with us.
 * 
 * Our trademark policy, <http://www.zarafa.com/zarafa-trademark-policy>,
 * allows you to use our trademarks in connection with Propagation and 
 * certain other acts regarding the Program. In any case, if you propagate 
 * an unmodified version of the Program you are allowed to use the term 
 * "Zarafa" to indicate that you distribute the Program. Furthermore you 
 * may use our trademarks where it is necessary to indicate the intended 
 * purpose of a product or service provided you use it in accordance with 
 * honest business practices. For questions please contact Zarafa at 
 * trademark@zarafa.com.
 *
 * The interactive user interface of the software displays an attribution 
 * notice containing the term "Zarafa" and/or the logo of Zarafa. 
 * Interactive user interfaces of unmodified and modified versions must 
 * display Appropriate Legal Notices according to sec. 5 of the GNU Affero 
 * General Public License, version 3, when you propagate unmodified or 
 * modified versions of the Program. In accordance with sec. 7 b) of the GNU 
 * Affero General Public License, version 3, these Appropriate Legal Notices 
 * must retain the logo of Zarafa or display the words "Initial Development 
 * by Zarafa" if the display of the logo is not reasonably feasible for
 * technical reasons.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *  
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_mapicalendar_WRAP_H_
#define SWIG_mapicalendar_WRAP_H_

#include <map>
#include <string>


class SwigDirector_RecurrencePatternInspector : public RecurrencePatternInspector, public Swig::Director {

public:
    SwigDirector_RecurrencePatternInspector(PyObject *self, ULONG cInterfaces, LPCIID lpInterfaces);
    virtual HRESULT SetPatternDaily(ULONG ulDailyPeriod);
    virtual HRESULT SetPatternWorkDays();
    virtual HRESULT SetPatternWeekly(ULONG ulFirstDayOfWeek, ULONG ulWeeklyPeriod, ULONG ulDayOfWeekMask);
    virtual HRESULT SetPatternAbsoluteMonthly(ULONG ulMonthlyPeriod, ULONG ulDayOfMonth);
    virtual HRESULT SetPatternRelativeMonthly(ULONG ulMonthlyPeriod, ULONG ulWhich, ULONG ulDayOfWeekMask);
    virtual HRESULT SetPatternAbsoluteYearly(ULONG ulYearlyPeriod, ULONG ulMonth, ULONG ulDayOfMonth);
    virtual HRESULT SetPatternRelativeYearly(ULONG ulYearlyPeriod, ULONG ulMonth, ULONG ulWhich, ULONG ulDayOfWeekMask);
    virtual HRESULT SetRangeNoEnd(ULONG ulStartDate);
    virtual HRESULT SetRangeNumbered(ULONG ulStartDate, ULONG ulOccurrences);
    virtual HRESULT SetRangeEndDate(ULONG ulStartDate, ULONG ulEndDate);


/* Internal Director utilities */
public:
    bool swig_get_inner(const char* swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }

    void swig_set_inner(const char* swig_protected_method_name, bool val) const
    { swig_inner[swig_protected_method_name] = val;}

private:
    mutable std::map<std::string, bool> swig_inner;


#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class RecurrencePatternInspector doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[10];
#endif

};


#endif
