'\" t
.\"     Title: za-aclsync
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: August 2011
.\"    Manual: Zarafa user reference
.\"    Source: Zarafa 7.1
.\"  Language: English
.\"
.TH "ZA\-ACLSYNC" "1" "August 2011" "Zarafa 7.1" "Zarafa user reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
za-aclsync \- Synchronizes archive ACL settings with those of the primary store\&.
.SH "SYNOPSIS"
.HP \w'\fBza\-aclsync\fR\ 'u
\fBza\-aclsync\fR [\fIOPTION\fR...] [\fIUSERS\fR...]
.SH "DESCRIPTION"
.PP
When a user has set permissions for others on his or her store or folders, the other user will need at least read\-permissions on this persons archive as well in order to read stubbed messages or access the archive directly\&. These permissions can not be set by the owner of the archive if the archive was attached without write privileges\&. Even if the user has write permissions, it\*(Aqs a nuisance to have to set all the permissions twice (or more if multiple archives are attached)\&.
.PP
\fBza\-aclsync\fR
can be used to propagate the ACL settings from the primary store to the archives\&. However, no user will ever get more right on a store or folder than the owner of the archive\&. So if the archive was attached without write permissions, no user will get write permissions on the archive\&.
.PP
For every archived foler in an archived store
\fBza\-aclsync \fRwill first determine the rights for the owner of the archive\&. Then it will get all the entries from the ACL of the current folder except those of the owner\&. Each right will be masked with the rights of the owner before being added to the ACL of the archive folder\&.
.SH "OPTIONS"
.PP
\fB\-h\fR \fIserverpath\fR
.RS 4
Host to connect with\&.
.sp
Default:
\fIfile:///var/run/zarafa \fR
.sp
Three formats are allowed for this option:
.sp
\fBUNIX socket\fR
: file://\fIpath_to_the_UNIX_socket\fR
.sp
\fBHTTP\fR
: http://\fIhost_or_IP\fR:\fIport\fR/zarafa
.sp
\fBSecure HTTP\fR
: https://\fIhost_or_IP\fR:\fIport\fR/zarafa
.RE
.PP
\fB\-s\fR \fIsslkey_file\fR
.RS 4
SSL key file for authentication\&.
.RE
.PP
\fB\-p\fR \fIsslkey_pass\fR
.RS 4
Password for the SSL key file\&.
.RE
.SH "AUTHOR"
.PP
Written by Zarafa\&.
