.\"     Title: zarafa-dagent.cfg
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: August 2011
.\"    Manual: Zarafa user reference
.\"    Source: Zarafa 7.0
.\"
.TH "ZARAFA\-DAGENT\&.CFG" "5" "August 2011" "Zarafa 7.0" "Zarafa user reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
zarafa-dagent.cfg \- The Zarafa dagent configuration file
.SH "SYNOPSIS"
.PP
\fBdagent\&.cfg\fR
.SH "DESCRIPTION"
.PP
The
\fIdagent\&.cfg\fR
is a configuration file for the Zarafa Dagent\&.
\fIdagent\&.cfg\fR
contains instructions for the software to set up the logging system and LMTP settings\&.
.SH "FILE FORMAT"
.PP
The file consists of one big section, but parameters can be grouped by functionality\&.
.PP
The parameters are written in the form:
.PP
\fBname\fR
=
\fIvalue\fR
.PP
The file is line\-based\&. Each newline\-terminated line represents either a comment, nothing, a parameter or a directive\&. A line beginning with `#\' is considered a comment, and will be ignored by Zarafa\&. Parameter names are case sensitive\&. Lines beginning with `!\' are directives\&.
.PP
Directives are written in the form:
.PP
!\fBdirective\fR
\fI[argument(s)] \fR
.PP
The following directives exist:
.PP
\fBinclude\fR
.RS 4
Include and process
\fIargument\fR
.sp
Example: !include common\&.cfg
.RE
.SH "EXPLANATION OF EACH PARAMETER"
.PP
\fBserver_bind\fR
.RS 4
IP address to bind to\&. 0\&.0\&.0\&.0 for any address\&.
.sp
Default:
\fI0\&.0\&.0\&.0\fR
.RE
.PP
\fBserver_socket\fR
.RS 4
Unix socket to find the connection to the Zarafa server\&.
.sp
Default:
\fIfile:///var/run/zarafa\fR
.RE
.PP
\fBrun_as_user\fR
.RS 4
After correctly starting, the dagent process will become this user, dropping root privileges\&. Note that the log file needs to be writeable by this user, and the directory too to create new logfiles after logrotation\&. This can also be achieved by setting the correct group and permissions\&.
.sp
Default value is empty, not changing the user after starting\&.
.RE
.PP
\fBrun_as_group\fR
.RS 4
After correctly starting, the dagent process will become this group, dropping root privileges\&.
.sp
Default value is empty, not changing the group after starting\&.
.RE
.PP
\fBpid_file\fR
.RS 4
Write the process ID number to this file\&. This is used by the init\&.d script to correctly stop/restart the service\&.
.sp
Default:
\fI/var/run/zarafa\-dagent\&.pid\fR
.RE
.PP
\fBsslkey_file\fR
.RS 4
Use this file as key to logon to the server\&. This is only used when server_socket is set to an HTTPS transport\&. See the
\fBzarafa-server\fR(1)
manual page on how to setup SSL keys\&.
.sp
Default: value not set\&.
.RE
.PP
\fBsslkey_pass\fR
.RS 4
The password of the SSL key file that is set in sslkey_file\&.
.sp
Default: value not set\&.
.RE
.PP
\fBlmtp_port\fR
.RS 4
Port to listen to for LMTP requests
.sp
Default:
\fI2003\fR
.RE
.PP
\fBlmtp_max_threads\fR
.RS 4
The maximum number of LMTP threads that can be running simultaneously\&. This is also limited by your SMTP server\&. (20 is the postfix default concurrency limit)
.sp
Default:
\fI20\fR
.RE
.PP
\fBspam_header_name\fR
.RS 4
To detect if the receiving mail is spam, the DAgent can check this header for a value that is in there\&. This name is case insensitive\&. If this option is empty, the detection method will be turned off\&. You can also force a delivery to the Junk Mail folder using the
\fI\-j\fR
commandline option\&.
.sp
Default:
\fIX\-Spam\-Status\fR
.RE
.PP
\fBspam_header_value\fR
.RS 4
When this value is found in the
\fIspam_header_name\fR, the mail will be considered spam, and will be delivered in the user\'s Junk Mail folder\&. The value can be anywhere in the header, not just the start\&. The value is case insensitive\&.
.sp
Default:
\fIYes,\fR
.RE
.PP
\fBlog_method\fR
.RS 4
The method which should be used for logging\&. Valid values are:
.PP
\fIsyslog\fR
.RS 4
Use the Linux system log\&. All messages will be written to the mail facility\&. See also
\fBsyslog.conf\fR(5)\&.
.RE
.PP
\fIfile\fR
.RS 4
Log to a file\&. The filename will be specified in
\fBlog_file\fR\&.
.RE
.sp
Default:
\fIfile\fR
.RE
.PP
\fBlog_file\fR
.RS 4
When logging to a file, specify the filename in this parameter\&. Use
\fI\-\fR
(minus sign) for stderr output\&.
.sp
Default:
\fI/var/log/zarafa/dagent\&.log\fR
.RE
.PP
\fBlog_timestamp\fR
.RS 4
Specify whether to prefix each log line with a timestamp in \'file\' logging mode\&.
.sp
Default:
\fI1\fR
.RE
.PP
\fBlog_level\fR
.RS 4
The level of output for logging in the range from 0 to 5\&. 0 means no logging, 5 means full logging\&.
.sp
Default:
\fI2\fR
.RE
.PP
\fBlog_raw_message\fR
.RS 4
Log the raw message to a file\&. The file is saved to the location specifed in
\fBlog_raw_message_path\fR\&.
.sp
Default:
\fIno\fR
.RE
.PP
\fBlog_raw_message_path\fR
.RS 4
Path to save the raw message\&.
.sp
Default:
\fI/tmp\fR
.RE
.PP
\fBarchive_on_delivery\fR
.RS 4
Archive incoming message on delivery\&. If an archive is attached to the target mailbox, the message will immediately be archived upon delivery\&.
.sp
Rules will be processed before the message is archived, so when a rule moves the message to an alternate location, the archived message will be placed in the correct location in the archive\&. When the incoming message is copied by a rule, only the original message is archived\&.
.sp
Default:
\fIno\fR
.RE
.PP
\fBmr_autoaccepter\fR
.RS 4
Zarafa\-dagent can auto\-accept meeting requests if the mr\-accept option is enabled for a user\&. When this option is enabled and a meeting request or meeting cancellation is received, this script is started with the following parameters: /usr/bin/zarafa\-mr\-accept <username> </path/to/dagent\&.cfg> [<ENTRYID>]\&.
.sp
If the script is successful (exitcode is 0), then no other actions are performed (eg rules or vacation messages) and the message is not delivered in the inbox\&. If the script exits with a non\-zero exit code, rules and vacation messages are run as usual, and the message is delivered in the inbox (or other folder, depending on rules or options)\&.
.sp
Default:
\fI/usr/bin/zarafa\-mr\-accept\fR
.RE
.PP
\fBplugin_enabled\fR
.RS 4
Enable or disable the dagent plugin framework\&.
.sp
Default:
\fIyes\fR
.RE
.PP
\fBplugin_manager_path\fR
.RS 4
The path to the dagent plugin manager\&.
.sp
Default:
\fI/usr/share/zarafa\-dagent/python\fR
.RE
.PP
\fBplugin_path\fR
.RS 4
Path to the activated dagent plugins\&. This folder contains symlinks to the zarafa plugins and custom scripts\&. The plugins are installed in \'/usr/share/zarafa\-dagent/python/plugins/\'\&. To activate a plugin create a symbolic link in the
\fIplugin_path\fR
directory\&.
.sp
Example: $ ln \-s /usr/share/zarafa\-dagent/python/plugins/BMP2PNG\&.py /var/lib/zarafa/dagent/plugins/BMP2PNG\&.py
.sp
Default:
\fI/var/lib/zarafa/dagent/plugins\fR
.RE
.SH "RELOADING"
.PP
The following options are reloadable by sending the zarafa\-dagent process a HUP signal:
.PP
log_level
.RS 4
.RE
.PP
archive_on_delivery
.RS 4
.RE
.PP
mr_autoaccepter
.RS 4
.RE
.SH "FILES"
.PP
\fI/etc/zarafa/dagent\&.cfg\fR
.RS 4
The Zarafa dagent configuration file\&.
.RE
.SH "AUTHOR"
.PP
Written by Zarafa\&.
.SH "SEE ALSO"
.PP

\fBzarafa-dagent\fR(1)
