'\" t
.\"     Title: zarafa-licensed
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: August 2011
.\"    Manual: Zarafa user reference
.\"    Source: Zarafa 7.0
.\"  Language: English
.\"
.TH "ZARAFA\-LICENSED" "1" "August 2011" "Zarafa 7.0" "Zarafa user reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
zarafa-licensed \- Start the Zarafa license server\&.
.SH "SYNOPSIS"
.HP \w'\fBzarafa\-licensed\fR\ 'u
\fBzarafa\-licensed\fR [\fIOPTION\fR...]
.SH "DESCRIPTION"
.PP
The zarafa\-licensed is used for license queries from non\-free parts of the Zarafa suite\&. If you wish to use any non\-free part of Zarafa, you will need to install, configure and run the zarafa\-licensed server\&.
.PP
The default settings of the zarafa\-licensed program are defined in
\fBzarafa-licensed.cfg\fR(5)\&.
.SH "OPTIONS"
.PP
Various options are possible\&. None of these options are required\&.
.PP
.PP
\fB\-\-config\fR, \fB\-c\fR \fIlicensed\&.cfg\fR
.RS 4
Specify the location of the licensed\&.cfg file\&. If the licensed\&.cfg file is not specified, the license server will continue using its default settings\&.
.sp
Default:
\fI/etc/zarafa/licensed\&.cfg\fR
.RE
.PP
\fB\-\-help\fR, \fB\-h\fR
.RS 4
Shows the help message of the license server\&.
.RE
.PP
\fB\-\-foreground\fR, \fB\-F\fR
.RS 4
Run in the foreground\&. Normally the license server will daemonize and run in the background\&.
.RE
.PP
\fB\-\-ignore\-unknown\-config\-options\fR
.RS 4
When unknown options exists in the configuration file the license service will report an error and shutdown\&. Pass this option to ignore unknown options so the license service will start\&.
.RE
.SH "SIGNALS"
.PP
The following signals can be sent to the zarafa\-license process:
.PP
\fBHUP\fR
.RS 4
When the HUP signal is received, some options from the configuration file are reloaded\&. The reloadable options are listed in the
\fBzarafa-licensed.cfg\fR(5)
manual page\&.
.sp
Also, when using
\fIlog_method = file\fR, the logfile will be closed and a new logfile will be opened\&. You can use this signal in your logrotate system\&.
.RE
.PP
\fBTERM\fR
.RS 4
To gracefully let the service exit, the normal TERM signal is used\&.
.RE
.SH "USAGE"
.PP
To start the license server:
.PP
\fBzarafa\-licensed\fR
.PP
The zarafa\-licensed process will keep running\&. You may also use the init\&.d scripts:
.PP
\fB/etc/init\&.d/zarafa\-licensed\fR
[\fIstart\fR|
\fIstop\fR|
\fIrestart\fR]
.SH "AUTHOR"
.PP
Written by Zarafa\&.
.SH "SEE ALSO"
.PP

\fBzarafa-licensed.cfg\fR(5)
\fBzarafa-server\fR(1)
