'\" t
.\"     Title: zarafa-report
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: August 2011
.\"    Manual: Zarafa user reference
.\"    Source: Zarafa 7.1
.\"  Language: English
.\"
.TH "ZARAFA\-REPORT" "1" "August 2011" "Zarafa 7.1" "Zarafa user reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
zarafa-report \- Creates a secure connection with https://report\&.zarafa\&.com/ for license reports\&.
.SH "SYNOPSIS"
.HP \w'\fBzarafa\-report\fR\ 'u
\fBzarafa\-report\fR [\fIOPTION\fR...]
.SH "DESCRIPTION"
.PP
In some setups, zarafa\-licensed needs to report license usage to Zarafa\&. This program will send these reports using HTTPS\&. This program will be automatically started by the
\fBzarafa\-licensed\fR
daemon\&.
.SH "OPTIONS"
.PP
The Zarafa report program takes the following configuration options:
.PP
\fB\-\-ca\-path\fR \fIca\-path\fR
.RS 4
Path to directory containg CA certificates\&.
.RE
.SH "AUTHOR"
.PP
Written by Zarafa\&.
