.\"     Title: zarafa-ldapms.cfg
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: August 2011
.\"    Manual: Zarafa user reference
.\"    Source: Zarafa 7.0
.\"
.TH "ZARAFA\-LDAPMS\&.CFG" "5" "August 2011" "Zarafa 7.0" "Zarafa user reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
zarafa-ldapms.cfg \- The Zarafa LDAP Multiserver configuration file
.SH "SYNOPSIS"
.PP
\fBldapms\&.cfg\fR
.SH "DESCRIPTION"
.PP
The
\fIldapms\&.cfg\fR
is a configuration file for LDAPMS user plugin, used for multiserver setups\&. All options to correctly retrieve user and group information can be set here\&.
.PP
Please rever to
\fBzarafa-ldap.cfg\fR(5)
for all normal LDAP settings\&. This manual page only discusses the extra options for multiserver environments\&.
.SH "FILE FORMAT"
.PP
The file consists of one big section, but parameters can be grouped by functionality\&.
.PP
The parameters are written in the form:
.PP
\fBname\fR
=
\fIvalue\fR
.PP
The file is line\-based\&. Each newline\-terminated line represents either a comment, nothing, a parameter or a directive\&. A line beginning with `#\' is considered a comment, and will be ignored by Zarafa\&. Parameter names are case sensitive\&. Lines beginning with `!\' are directives\&.
.PP
Directives are written in the form:
.PP
!\fBdirective\fR
\fI[argument(s)] \fR
.PP
The following directives exist:
.PP
\fBinclude\fR
.RS 4
Include and process
\fIargument\fR
.sp
Example: !include common\&.cfg
.RE
.SH "EXPLANATION OF EACH PARAMETER"
.PP
\fBldap_user_server_attribute\fR
.RS 4
This value is the unique name of the server on which the users store is available\&.
.sp
Default:
\fIzarafaUserServer\fR
.RE
.PP
\fBldap_company_server_attribute\fR
.RS 4
This value is the unique name of the server on which the public store for a tenant is available\&.
.sp
Default:
\fIzarafaCompanyServer\fR
.RE
.PP
\fBldap_server_address_attribute\fR
.RS 4
The attribute which contains the address of the server\&. This is used by servers to redirect a client to the correct server\&.
.sp
Default: Empty
.RE
.PP
\fBldap_server_http_port_attribute\fR
.RS 4
The attribute that contains the port on which the server listens for HTTP connections\&.
.sp
Default:
\fIzarafaHttpPort\fR
.RE
.PP
\fBldap_server_ssl_port_attribute\fR
.RS 4
The attribute that contains the port on which the server listens for SSL connections\&.
.sp
Default:
\fIzarafaSslPort\fR
.RE
.PP
\fBldap_server_file_path_attribute\fR
.RS 4
The attribute that contains the path on which the server listens for unix socket connections in Linux or named pipe connections in MS Windows\&.
.sp
Default:
\fIzarafaSslPort\fR
.RE
.PP
\fBldap_server_proxy_url_attribute\fR
.RS 4
If the node is accessed through a reverse HTTP proxy, it should be accessed using this URL\&. See the manual page entry of proxy_header in the
\fBzarafa-server.cfg\fR(5)
manpage for details on when this value is used\&.
.sp
Default:
\fIzarafaProxyURL\fR
.RE
.PP
\fBldap_server_contains_public_attribute\fR
.RS 4
The attribute that determines if a server contains the public store for a non\-hosted environment\&.
.sp
Default:
\fIzarafaContainsPublic\fR
.RE
.PP
\fBldap_server_search_filter\fR
.RS 4
Add an extra filter to the server search\&.
.sp
Default for OpenLDAP is empty\&.
.sp
Default for ADS:
\fI(objectClass=Computer)\fR
.RE
.PP
\fBldap_server_unique_attribute\fR
.RS 4
This is the unique attribute of a server which is never going to change, unless the server is removed from LDAP\&.
.sp
Default:
\fIcn\fR
.RE
.SH "FILES"
.PP
\fI/etc/zarafa/server\&.cfg\fR
.RS 4
The server configuration file\&.
.RE
.PP
\fI/etc/zarafa/ldap\&.cfg\fR
.RS 4
The Zarafa LDAP configuration file\&.
.RE
.SH "AUTHOR"
.PP
Written by Zarafa\&.
.SH "SEE ALSO"
.PP

\fBzarafa-server\fR(1)
\fBzarafa-server.cfg\fR(5)
