.\"     Title: zarafa
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: August 2011
.\"    Manual: Zarafa user reference
.\"    Source: Zarafa 7.0
.\"
.TH "ZARAFA" "1" "August 2011" "Zarafa 7.0" "Zarafa user reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
zarafa \- Zarafa server overview.
.SH "DESCRIPTION"
.PP
Zarafa is a full\-featured e\-mail and groupware solution, focused towards clients using the MAPI standard\&. The Zarafa suite consists of the following parts:
.PP
zarafa\-server
.RS 4
The main server process, accepting client connections, and managing storage and retrieval of data from the database\&.
.RE
.PP
zarafa\-spooler
.RS 4
The outgoing e\-mail spooler\&. This service makes sure that e\-mails sent by clients are converted to internet e\-mail and forwarded to an SMTP server\&.
.RE
.PP
zarafa\-dagent
.RS 4
The Zarafa delivery agent is called by your MTA to deliver an incoming e\-mail message into a user\'s inbox\&.
.RE
.PP
zarafa\-admin
.RS 4
The admin program can be started from the command line to perform various administrational tasks such add creating users, and managing groups\&.
.RE
.PP
zarafa\-monitor
.RS 4
The monitor server process monitors user stores for quota limits\&. When a user goes over the warning quota level, zarafa\-monitor will issue a warning e\-mail\&.
.RE
.PP
zarafa\-gateway
.RS 4
The gateway server process enables POP3 and/or IMAP connectivity to the Zarafa server\&. Users with other non\-Outlook or webaccess clients can still retreive their e\-mail from the server\&.
.RE
.PP
zarafa\-passwd
.RS 4
The passwd program can be started from the command line to update the user password when the server is running with dbplugin\&.
.RE
.PP
zarafa\-fsck
.RS 4
The fsck program can be started from the command line to check and possibly fix broken items in your calendar or tasks folder\&.
.RE
.PP
zarafa\-backup
.RS 4
The backup tool creates an incremental dump of a store\&. The data can be restored by the
\fBzarafa\-restore\fR
tool\&. This tool can be used as a brick\-level\-backup\&. It can not be used as a disaster\-recovery tool\&.
.RE
.PP
zarafa\-restore
.RS 4
The restore tool reads data from a backup create by
\fBzarafa\-backup\fR\&. You can restore single items or folders\&. To restore a complete store, you can use the example script found in
\fI/usr/share/zarafa/zarafa\-backup\-helpers\fR\&.
.RE
.PP
zarafa\-ical
.RS 4
The iCal/CalDAV gateway enables users to retrieve their own Zarafa calendar using the iCalendar standard\&.
.RE
.PP
zarafa\-licensed
.RS 4
The zarafa\-licensed daemon is used for licensing query information from non\-free parts of the zarafa product\&. You must run this daemon if you wish to use non\-free components of the zarafa product, like access from Windows environments\&.
.RE
.PP
zarafa\-report
.RS 4
A reporting program used by zarafa\-licensed to send license reports to the zarafa\-server using a secured connection\&.
.RE
.PP
zarafa\-stats
.RS 4
A simple program that dumps some statistics the zarafa\-server program collects\&.
.RE
.PP
zarafa\-cfgchecker
.RS 4
This program tests for common configuration errors for a given config file\&.`
.RE
.PP
zarafa\-indexer
.RS 4
The zarafa\-indexer daemon is used to index all messages for all users in the zarafa\-server\&. Indexing messages greatly enhances the search performance of the zarafa\-server\&.
.RE
.SH "AUTHOR"
.PP
Written by Zarafa\&.
.SH "SEE ALSO"
.PP

\fBzarafa-server\fR(1)
\fBzarafa-spooler\fR(1)
\fBzarafa-dagent\fR(1)
\fBzarafa-admin\fR(1)
\fBzarafa-monitor\fR(1)
\fBzarafa-gateway\fR(1)
\fBzarafa-passwd\fR(1)
\fBzarafa-fsck\fR(1)
\fBzarafa-backup\fR(1)
\fBzarafa-restore\fR(1)
\fBzarafa-ical\fR(1)
\fBzarafa-licensed\fR(1)
\fBzarafa-report\fR(1)
\fBzarafa-stats\fR(1)
\fBzarafa-cfgchecker\fR(1)
\fBzarafa-indexer\fR(1)
