'\" t
.\"     Title: zarafa-indexer
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: August 2011
.\"    Manual: Zarafa user reference
.\"    Source: Zarafa 7.0
.\"  Language: English
.\"
.TH "ZARAFA\-INDEXER" "1" "August 2011" "Zarafa 7.0" "Zarafa user reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
zarafa-indexer \- Zarafa Indexer Service\&.
.SH "SYNOPSIS"
.HP \w'\fBzarafa\-indexer\fR\ 'u
\fBzarafa\-indexer\fR
.SH "DESCRIPTION"
.PP
The zarafa\-indexer daemon is used to index all messages for all users in the zarafa\-server\&. Indexing messages greatly enhances the search performance of the zarafa\-server\&.
.PP
After starting, the indexer will periodically update the store index files and will keep listening for connections on the configured TCP port and/or Unix socket for search requests from the zarafa\-server\&.
.SH "OPTIONS"
.PP
The Zarafa server program takes the following configuration options:
.PP
\fB\-\-config\fR, \fB\-c\fR \fIfile\fR
.RS 4
Specify the location of the configuration file\&.
.sp
Default:
\fI/etc/zarafa/indexer\&.cfg\fR
.RE
.PP
\fB\-\-foreground\fR, \fB\-F\fR
.RS 4
Run in the foreground\&. Normally the indexer will daemonize and run in the background\&.
.RE
.PP
\fB\-\-host\fR, \fB\-h\fR \fIpath\fR
.RS 4
Connect to the Zarafa server through
\fIpath\fR, e\&.g\&.
file:///path/to/socket\&. Default:
file:///var/run/zarafa\&.
.RE
.PP
\fB\-V\fR
.RS 4
Print the version and exit\&.
.RE
.PP
\fB\-\-ignore\-unknown\-config\-options\fR
.RS 4
When unknown options exists in the configuration file the indexer will report an error and shutdown\&. Pass this option to ignore unknown options so the indexer will start\&.
.RE
.PP
When invoked with no options, the indexer will search for a configuration file in
/etc/zarafa/indexer\&.cfg\&. If no configuration file is found, default values are used\&. See
\fBzarafa-indexer.cfg\fR(5)
for all configuration options and their default values\&.
.PP
Options for Windows NT/XP/2003 only:
.PP
\fB\-v\fR
.RS 4
Check the version of the installed Windows service\&.
.RE
.PP
\fB\-i\fR
.RS 4
Register the Windows service\&.
.RE
.PP
\fB\-u\fR
.RS 4
Deregister the Windows service\&.
.RE
.SH "USAGE"
.PP
Starting the indexer with an alternative configuration:
.PP

\fBzarafa\-indexer\fR
\fB\-c\fR
\fI/path/to/indexer\&.cfg\fR
.PP
You may also use the init\&.d scripts:
.PP
\fB/etc/init\&.d/zarafa\-indexer\fR
[\fIstart\fR|
\fIstop\fR|
\fIrestart\fR|
\fIreload\fR]
.SH "AUTHOR"
.PP
Written by Zarafa\&.
.SH "SEE ALSO"
.PP

\fBzarafa-server\fR(1)
\fBzarafa-indexer.cfg\fR(5)
