.\"     Title: zarafa-licensed.cfg
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: August 2011
.\"    Manual: Zarafa user reference
.\"    Source: Zarafa 7.0
.\"
.TH "ZARAFA\-LICENSED\&.C" "5" "August 2011" "Zarafa 7.0" "Zarafa user reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
zarafa-licensed.cfg \- The Zarafa licensed configuration file
.SH "SYNOPSIS"
.PP
\fBlicensed\&.cfg\fR
.SH "DESCRIPTION"
.PP
The
\fIlicensed\&.cfg\fR
is a configuration file for the Zarafa license server\&.
\fIlicensed\&.cfg\fR
contains instructions for the software to set up the logging system and the licensing part of Zarafa\&.
.SH "FILE FORMAT"
.PP
The file consists of one big section, but parameters can be grouped by functionality\&. The types of parameters are: server and log\&.
.PP
The parameters are written in the form
.PP

\fIname\fR
=
\fBvalue\fR
.PP
The file is line\-based \- that is, each newline\-terminated line represents either a comment, nothing or a parameter\&.
.PP
A line beginning with # is considered a comment, and will be ignored by Zarafa\&.
.PP
Parameter names are case sensitive\&.
.SH "EXPLANATION OF EACH PARAMETER"
.PP
\fBserver_pipe_name\fR
.RS 4
Unix socket to listen on\&.
.sp
Default:
\fI/var/run/zarafa\-licensed\fR
.RE
.PP
\fBserver_socket\fR
.RS 4
Unix socket to find the connection to the Zarafa server\&.
.sp
Default:
\fIfile:///var/run/zarafa\fR
.RE
.PP
\fBsslkey_file\fR
.RS 4
Use this file as key to logon to the server\&. This is only used when server_socket is set to an HTTPS transport\&. See the
\fBzarafa-server\fR(1)
manual page on how to setup SSL keys\&.
.sp
Default: value not set\&.
.RE
.PP
\fBsslkey_pass\fR
.RS 4
The password of the SSL key file that is set in sslkey_file\&.
.sp
Default: value not set\&.
.RE
.PP
\fBlicense_path\fR
.RS 4
The path to the license directory\&. This directory should contain a file named
\fIbase\fR
with the serial number\&. All other files in this directory can contain a CALs (Client Access License), one per file\&.
.sp
Default:
\fI/etc/zarafa/license\fR
.RE
.PP
\fBrun_as_user\fR
.RS 4
After correctly starting, the server process will become this user, dropping root privileges\&. Note that the log file needs to be writeable by this user, and the directory too to create new logfiles after logrotation\&. This can also be achieved by setting the correct group and permissions\&.
.sp
Default value is empty, not changing the user after starting\&.
.RE
.PP
\fBrun_as_group\fR
.RS 4
After correctly starting, the server process will become this group, dropping root privileges\&.
.sp
Default value is empty, not changing the group after starting\&.
.RE
.PP
\fBpid_file\fR
.RS 4
Write the process ID number to this file\&. This is used by the init\&.d script to correctly stop/restart the service\&.
.sp
Default:
\fI/var/run/zarafa\-licensed\&.pid\fR
.RE
.PP
\fBrunning_path\fR
.RS 4
Change directory to this path when running in daemonize mode\&. When using the \-F switch to run in the foreground the directory will not be changed\&.
.sp
Default:
\fI/\fR
.RE
.PP
\fBlog_method\fR
.RS 4
The method which should be used for logging\&. Valid values are:
.PP
\fIsyslog\fR
.RS 4
Use the Linux system log\&. All messages will be written to the mail facility\&. See also
\fBsyslog.conf\fR(5)\&.
.RE
.PP
\fIfile\fR
.RS 4
Log to a file\&. The filename will be specified in
\fBlog_file\fR\&.
.RE
.sp
Default:
\fIfile\fR
.RE
.PP
\fBlog_file\fR
.RS 4
When logging to a file, specify the filename in this parameter\&. Use
\fI\-\fR
(minus sign) for stderr output\&.
.sp
Default:
\fI/var/log/zarafa/licensed\&.log\fR
.RE
.PP
\fBlog_timestamp\fR
.RS 4
Specify whether to prefix each log line with a timestamp in \'file\' logging mode\&.
.sp
Default:
\fI1\fR
.RE
.PP
\fBlog_level\fR
.RS 4
The level of output for logging in the range from 0 to 5\&. 0 means no logging, 5 means full logging\&.
.sp
Default:
\fI2\fR
.RE
.PP
\fBreport_path\fR
.RS 4
The path to a directory where to store the report logging\&. Report logging is only enabled if you have a report\-based license from Zarafa\&.
.sp
Default:
\fI/var/lib/zarafa/report\fR
.RE
.PP
\fBreport_ca\fR
.RS 4
The path to a directory containing the SSL CA information for zarafa\-report\&. This is needed for secure upload of your license information if your license requires this\&.
.sp
Default:
\fI/etc/zarafa/report\-ca\fR
.RE
.SH "RELOADING"
.PP
The following options are reloadable by sending the zarafa\-licensed process a HUP signal:
.PP
log_level
.RS 4
.RE
.SH "FILES"
.PP
\fI/etc/zarafa/licensed\&.cfg\fR
.RS 4
The Zarafa license server configuration file\&.
.RE
.SH "AUTHOR"
.PP
Written by Zarafa\&.
.SH "SEE ALSO"
.PP

\fBzarafa-licensed\fR(1)
