.\"     Title: zarafa-indexer.cfg
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: August 2011
.\"    Manual: Zarafa user reference
.\"    Source: Zarafa 7.0
.\"
.TH "ZARAFA\-INDEXER\&.CF" "5" "August 2011" "Zarafa 7.0" "Zarafa user reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
zarafa-indexer.cfg \- The Zarafa Indexer configuration file
.SH "SYNOPSIS"
.PP
\fBindexer\&.cfg\fR
.SH "DESCRIPTION"
.PP
The
\fIindexer\&.cfg\fR
is a configuration file for the Zarafa Indexer Service\&.
\fIindexer\&.cfg\fR
contains instructions for the software to set up the connection, indexing and logging systems\&.
.SH "FILE FORMAT"
.PP
The file consists of one big section, but parameters can be grouped by functionality\&.
.PP
The parameters are written in the form:
.PP
\fBname\fR
=
\fIvalue\fR
.PP
The file is line\-based\&. Each newline\-terminated line represents either a comment, nothing, a parameter or a directive\&. A line beginning with `#\' is considered a comment, and will be ignored by Zarafa\&. Parameter names are case sensitive\&. Lines beginning with `!\' are directives\&.
.PP
Directives are written in the form:
.PP
!\fBdirective\fR
\fI[argument(s)] \fR
.PP
The following directives exist:
.PP
\fBinclude\fR
.RS 4
Include and process
\fIargument\fR
.sp
Example: !include common\&.cfg
.RE
.SH "EXPLANATION OF THE SERVER SETTINGS PARAMETERS"
.PP
\fBserver_socket\fR
.RS 4
Socket to find the connection to the Zarafa server\&.
.sp
Default:
\fIfile:///var/run/zarafa\fR
.RE
.PP
\fBrun_as_user\fR
.RS 4
After correctly starting, the server process will become this user, dropping root privileges\&. Note that the log file needs to be writeable by this user, and the directory too to create new logfiles after logrotation\&. This can also be achieved by setting the correct group and permissions\&.
.sp
Default value is empty, not changing the user after starting\&.
.RE
.PP
\fBrun_as_group\fR
.RS 4
After correctly starting, the server process will become this group, dropping root privileges\&.
.sp
Default value is empty, not changing the group after starting\&.
.RE
.PP
\fBpid_file\fR
.RS 4
Write the process ID number to this file\&. This is used by the init\&.d script to correctly stop/restart the service\&.
.sp
Default:
\fI/var/run/zarafa\-indexer\&.pid\fR
.RE
.PP
\fBrunning_path\fR
.RS 4
Change directory to this path when running in daemonize mode\&. When using the \-F switch to run in the foreground the directory will not be changed\&.
.sp
Default:
\fI/\fR
.RE
.PP
\fBcleanup_lockfiles\fR
.RS 4
If for some unfortunate reason the zarafa\-indexer is not cleanly stopped, it may leave lockfiles behind on stores it was processing\&. To continue the indexing on this possibly corrupt index, you need to remove the lockfile\&. To restart the index of the store, you need to remove the complete index directory\&. This directory will be mentioned in the log\&. You may choose to automatically remove the lockfiles by setting this option to yes\&. The index will be left on disk\&.
.sp
Default:
\fIno\fR
.RE
.PP
\fBlimit_results\fR
.RS 4
Limit the number of results returned to the server\&. If set to a nonzero value, only the N most relevant results will be returned to the server\&. This in turn limits the number of results that the user will see\&. If the limit is set to 0, all results will be returned\&.
.sp
Default:\fI0\fR
.RE
.SH "EXPLANATION OF THE SSL SETTINGS PARAMETERS"
.PP
\fBssl_key_file\fR
.RS 4
The file containing the private key and certificate\&. Please read the SSL section in the
\fBzarafa-server\fR(1)
manual on how to create this file\&.
.sp
Default:
\fI/etc/zarafa/ssl/indexer\&.pem\fR
.RE
.PP
\fBssl_key_pass\fR
.RS 4
Enter you password here when your key file contains a password to be readable\&.
.sp
No default set\&.
.RE
.PP
\fBssl_private_key_file\fR
.RS 4
The indexer will use this file as private key for SSL TLS\&. This file can be created with:
\fBopenssl genrsa \-out /etc/zarafa/indexer/privkey\&.pem 2048\fR\&.
.sp
Default:
\fI/etc/zarafa/indexer/privkey\&.pem\fR
.RE
.PP
\fBssl_certificate_file\fR
.RS 4
The indexer will use this file as certificate for SSL TLS\&. A self\-signed certificate can be created with:
\fBopenssl req \-new \-x509 \-key /etc/zarafa/indexer/privkey\&.pem \-out /etc/zarafa/indexer/cert\&.pem \-days 1095\fR\&.
.sp
Default:
\fI/etc/zarafa/indexer/cert\&.pem\fR
.RE
.SH "EXPLANATION OF THE LOGGING SETTINGS PARAMETERS"
.PP
\fBlog_method\fR
.RS 4
The method which should be used for logging\&. Valid values are:
.PP
\fIsyslog\fR
.RS 4
Use the Linux system log\&. All messages will be written to the mail facility\&. See also
\fBsyslog.conf\fR(5)\&.
.RE
.PP
\fIfile\fR
.RS 4
Log to a file\&. The filename will be specified in
\fBlog_file\fR\&.
.RE
.sp
Default:
\fIfile\fR
.RE
.PP
\fBlog_file\fR
.RS 4
When logging to a file, specify the filename in this parameter\&. Use
\fI\-\fR
(minus sign) for stderr output\&.
.sp
Default:
\fI\-\fR
.RE
.PP
\fBlog_level\fR
.RS 4
The level of output for logging in the range from 0 to 5\&. 0 means no logging, 5 means full logging\&.
.sp
Default:
\fI2\fR
.RE
.PP
\fBlog_timestamp\fR
.RS 4
Specify whether to prefix each log line with a timestamp in \'file\' logging mode\&.
.sp
Default:
\fI1\fR
.RE
.SH "EXPLANATION OF THE INDEXER SETTINGS PARAMETERS"
.PP
\fBserver_bind_name\fR
.RS 4
Connection path to which other processes can connect with the zarafa\-indexer for performing search queries\&.
.sp
Use
\fIhttp://0\&.0\&.0\&.0:port\fR
to listen as an HTTP service on all network interfaces on the given
\fIport\fR
number\&.
.sp
Default:
\fIfile:///var/run/zarafa\-indexer\fR
.RE
.PP
\fBindex_path\fR
.RS 4
Base directory under which all index files will be placed, the hierarchy below this folder will be: ${index_path}/${server}/${user}/index
.sp
Default:
\fI/var/lib/zarafa/index/\fR
.RE
.PP
\fBindex_sync_stream\fR
.RS 4
Enable streaming synchronization\&. This can increase synchronization speed depending on the setup\&. During streaming synchronization all messages which will be synchronized will be downloaded in a single call requiring more overall memory\&. When
\fIindex_attachments\fR
is disabled streaming will cause overhead because all attachments will be downloaded to the client even though they will not be indexed\&.
.sp
This option requires
\fIenable_enhanced_ics\fR
to be enabled in the
\fBzarafa-server.cfg\fR(5), otherwise the indexing will still fallback to the slower synchronization\&.
.sp
Default:
\fIyes\fR
.RE
.PP
\fBindex_interval\fR
.RS 4
Interval (in minutes) for indexing\&. During every interval the zarafa\-indexer will synchronize with the zarafa\-server to collect all changes for each store and update the index files for the stores accordingly\&.
.sp
Default:
\fI5\fR
minutes
.RE
.PP
\fBindex_threads\fR
.RS 4
Maximum number if indexing threads\&. In a multi\-server environment it is possible to distribute the work for different zarafa\-servers over different indexing threads\&. Note that the work for a single server will be exclusively assigned to a single thread, thus the number of started indexing threads will never exceed the number of zarafa\-servers\&.
.sp
Default:
\fI1\fR
.RE
.PP
\fBindex_max_field_length\fR
.RS 4
Maximum number of words from a single message to index\&. Only the first
\fIindex_max_field_length\fR
from a single message will be indexed, all words above this value will be discarded\&.
.sp
This value is used to control the amount of required memory during the indexing process\&. More memory will be required during indexing when
\fIindex_max_field_length\fR
is set to a higher value\&.
.sp
Default:
\fI10000\fR
.RE
.PP
\fBindex_merge_factor\fR
.RS 4
Number of index file segments per store before Lucene merges the segments into a single file\&.
.sp
A low value will cause less memory to be used during indexing, but the increased IO access to disk causes the indexing process to be slower, while searching will be faster\&. A high value will speed up the indexing process while searching will be slower
.PP
\fIBatch indexing\fR
.RS 4
If
\fIindex_interval\fR
is set to a high value, set
\fIindex_merge_factor\fR
to a high value (> 10)\&.
.RE
.PP
\fIInteractive indexing\fR
.RS 4
If
\fIindex_interval\fR
is set to a low value, set
\fIindex_merge_factor\fR
to a low value (< 10)\&.
.RE
.sp
Default:
\fI10\fR
.RE
.PP
\fBindex_max_buffered_docs\fR
.RS 4
Max number of documents kept in memory before CLucene will write a new index file segment to disk\&.
.sp
Larger values will increase memory usage but makes the indexing process faster\&.
.sp
Default:
\fI10\fR
.RE
.PP
\fBindex_min_merge_docs\fR
.RS 4
Minumum number of messages in a single store which are indexed in memory before the index writer flushes the index to disk as new index file segment\&.
.sp
Creating new index file segments often increases IO access to disk but reduces the amount of memory required during the indexing process\&.
.sp
Default:
\fI10\fR
.RE
.PP
\fBindex_max_merge_docs\fR
.RS 4
Maximum number of documents in a index file segment, when an index file segment contains
\fIindex_max_merge_docs\fR
documents it will no longer be merged with other index file segments\&.
.sp
This will limit the total size of an index file segment but will trigger more index file segments to be created\&.
.PP
\fIBatch indexing\fR
.RS 4
If
\fIindex_interval\fR
is set to a high value, set
\fIindex_max_merge_docs\fR
to a high value (> 10000)\&.
.RE
.PP
\fIInteractive indexing\fR
.RS 4
If
\fIindex_interval\fR
is set to a low value, set
\fIindex_max_merge_docs\fR
to a low value (< 10000)\&.
.RE
.sp
Default:
\fI2147483647\fR
(INT32_MAX)
.RE
.PP
\fBindex_term_interval\fR
.RS 4
The fraction of terms in the "dictionary" which should be stored in memory\&. Smaller values use more memory, but make searching slightly faster, while larger values use less memory and make searching slightly slower\&. Searching is typically not dominated by dictionary lookup, so tweaking this is rarely useful\&.
.sp
Default:
\fI128\fR
.RE
.PP
\fBindex_cache_timeout\fR
.RS 4
Timeout value (in seconds) for purging all caches used during the indexing process\&. If set to
\fI0\fR
caching will be disabled\&.
.sp
Default:
\fI0\fR
.RE
.SH "EXPLANATION OF THE ATTACHMENT INDEXER SETTINGS PARAMETERS"
.PP
\fBindex_attachments\fR
.RS 4
Enable indexing of attachments\&. When attachments are being indexed, searching for keywords in the body of a message will automatically cause the attachment to be searched as well\&.
.sp
This will slow down the indexing process, require more system memory and increases index file size\&.
.sp
Default:
\fIno\fR
.RE
.PP
\fBindex_attachment_max_size\fR
.RS 4
Maxiumum file size for attachments to be indexed\&. Any attachment larger then this amount (in kilobytes) will not be indexed\&.
.sp
Default:
\fI5120\fR
.RE
.PP
\fBindex_attachment_parser\fR
.RS 4
For indexing attachment each file must be converted into plain\-text by a parser\&. For this purpose the
\fIattachments_parser\fR
script has been installed which can be configured to parse specific mime\-types\&.
.sp
It is highly advisable to check the
\fIattachments_parser\&.db\fR
file to add or remove parser command for specific mime\-types and/or file\-extensions\&.
.sp
Default:
\fI/etc/zarafa/indexerscripts/attachments_parser\fR
.RE
.PP
\fBindex_attachment_parser_max_memory\fR
.RS 4
Limit the maximum amount of memory (in bytes) the parser may use for converting the attachment into plain\-text\&. If this limit is exceeded the parser will be killed and the attachment will not be completely converted\&. If the value is set to
\fI0\fR
the limit is considered as infinite\&.
.sp
The attachment parser depends on external tools to convert attachments to plain\-text, by limiting the amount of resources the parser is allowed to use problems can be prevented when the selected external tool misbehaves with certain attachments\&.
.sp
Default:
\fI0\fR
bytes
.RE
.PP
\fBindex_attachment_parser_max_cputime\fR
.RS 4
Limit the maximum cpu time (in seconds) the parser may use for converting the attachment into plain\-text\&. If this limit is exceeded the parser will be killed and the attachment will not be completely converted\&. If the value is set to
\fI0\fR
the limit is considered as infinite\&.
.sp
The attachment parser depends on external tools to convert attachments to plain\-text, by limiting the amount of resources the parser is allowed to use problems can be prevented when the selected external tool misbehaves with certain attachments\&.
.sp
Default:
\fI0\fR
seconds
.RE
.PP
\fBindex_attachment_mime_filter\fR
.RS 4
Some attachments are not intresting to run through the parser\&. With this option you can filter out attachment which have a specific mimetype\&. Only the first part of the mimetype should be given here\&. Good examples of a mimetype to filter is \'image\', \'audio\' and \'video\'\&. This field is space separated\&.
.sp
Default:
.RE
.PP
\fBindex_attachment_extension_filter\fR
.RS 4
As the mime filter above, but works on the attachment extension\&. This is only tested if the mimetype of an attachment was unknown\&. Good examples of an extension to filter is \'gif\', \'jpeg\', \'jpg\' and \'png\'\&. This field is space separated\&.
.sp
Default:
.RE
.PP
\fBindex_max_clauses\fR
.RS 4
This is the maximum number of clauses that can be present in a Lucene search query, after expansion\&. You can raise this limit if you are experiencing a Too Many Clauses error during searches\&.
.sp
Default:
\fI50000\fR
clauses
.RE
.SH "EXPLANATION OF THE INDEX FILTERS SETTINGS PARAMETERS"
.PP
\fBindex_block_users\fR
.RS 4
A list of usernames which should not be indexed by the indexing service\&. Fields in the list are seperated by a SPACE\&.
.sp
Default: empty
.RE
.PP
\fBindex_block_companies\fR
.RS 4
A list of tentants which should not be indexed by the indexing service\&. All users and the public store belonging to these tentants will not be indexed\&. Fields in the list are seperated by a SPACE\&.
.sp
Default: empty
.RE
.PP
\fBindex_allow_servers\fR
.RS 4
A list of server names which should be indexed by the indexing service\&. All stores located on these servers will be indexed, all other servers will be ignored\&. If kept empty, no filtering is applied and all detected servers are indexed\&. Fields in the list are seperated by a SPACE\&.
.sp
Default: empty
.RE
.SH "RELOADING"
.PP
The following options are reloadable by sending the zarafa\-indexer process a HUP signal:
.PP
log_level
.RS 4
.RE
.PP
index_threads
.RS 4
.RE
.PP
index_max_field_length
.RS 4
.RE
.PP
index_merge_factor
.RS 4
.RE
.PP
index_max_buffered_docs
.RS 4
.RE
.PP
index_min_merge_docs
.RS 4
.RE
.PP
index_max_merge_docs
.RS 4
.RE
.PP
index_term_interval
.RS 4
.RE
.PP
index_attachments
.RS 4
.RE
.PP
index_attachment_max_size
.RS 4
.RE
.PP
index_attachment_parser
.RS 4
.RE
.PP
index_attachment_parser_max_memory
.RS 4
.RE
.PP
index_attachment_parser_max_cputime
.RS 4
.RE
.PP
index_attachment_mime_filter
.RS 4
.RE
.PP
index_attachment_extension_filter
.RS 4
.RE
.SH "AUTHOR"
.PP
Written by Zarafa\&.
.SH "SEE ALSO"
.PP

\fBzarafa-indexer\fR(1)
