.\"     Title: zarafa-report
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: August 2011
.\"    Manual: Zarafa user reference
.\"    Source: Zarafa 7.0
.\"
.TH "ZARAFA\-REPORT" "1" "August 2011" "Zarafa 7.0" "Zarafa user reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
zarafa-report \- Creates a secure connection with https://report.zarafa.com/ for license reports.
.SH "SYNOPSIS"
.HP 14
\fBzarafa\-report\fR [\fIOPTION\fR...]
.SH "DESCRIPTION"
.PP
In some setups, zarafa\-licensed needs to report license usage to Zarafa\&. This program will send these reports using HTTPS\&. This program will be automatically started by the
\fBzarafa\-licensed\fR
daemon\&.
.SH "OPTIONS"
.PP
The Zarafa report program takes the following configuration options:
.PP
\fB\-\-ca\-path\fR \fIca\-path\fR
.RS 4
Path to directory containg CA certificates\&.
.RE
.SH "AUTHOR"
.PP
Written by Zarafa\&.
