.\"     Title: zarafa-backup
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: August 2011
.\"    Manual: Zarafa user reference
.\"    Source: Zarafa 7.0
.\"
.TH "ZARAFA\-BACKUP" "1" "August 2011" "Zarafa 7.0" "Zarafa user reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
zarafa-backup \- The Zarafa Backup tool
.SH "SYNOPSIS"
.HP 14
\fBzarafa\-backup\fR [\fIOPTION\fR...]
.SH "DESCRIPTION"
.PP
The zarafa\-backup tool creates a backup of a store\&. The data of emails, calender items, contacts, etc\&. are stored in a binary file\&. You can use the zarafa\-restore tool to retreive backed up items\&.
.PP
Some items are not backed up, like the rules created by the user, specific view information, selected sorting, etc\&.
.PP
Therefore, this backup tool cannot be used as a disaster recovery method\&. Please refer to the \'Zarafa Backup & Performance\' documentation on the Zarafa site for common available backup methods\&.
.PP
The backup tool currently automatically detects if a full backup or an incremental backup is possible\&. This may change in the future\&.
.SH "INDEX FILE LAYOUT"
.PP
The backup tool will create 2 files for each store that is backed up\&. username\&.data\&.zbk will contain the data of the store\&. username\&.index\&.zbk is an text index of data data file\&. The file contains a number of fields per line, separated by a colon\&. The first field is either \'R\' (root), \'C\' (container) or \'M\' (message)\&. The Root line contains 4 fields:
.PP
1st field: marker
.RS 4
R: Root marker
.RE
.PP
2nd field: unique id length
.RS 4
[0\-9]+: number of characters in following id
.RE
.PP
3rd field: unique id
.RS 4
The unique id of the root\&. This key matches the parent field of containers which are directly on the root level, eg\&. Inbox, Outbox, Calendar, etc\&.
.RE
.PP
4th field: username
.RS 4
The name of the user of the backup\&.
.RE
.PP
A container line contains 11 fields:
.PP
1st field: marker
.RS 4
C: Container marker
.RE
.PP
2nd field: unique parent id length
.RS 4
[0\-9]+: number of characters in following id
.RE
.PP
3rd field: unique parent id
.RS 4
The unique id of the parent of this container\&. This key matches the id field of the parent container\&.
.RE
.PP
4th field: unique id length
.RS 4
[0\-9]+: number of characters in following id
.RE
.PP
5th field: unique id
.RS 4
The unique id of this container\&. Other containers and messages may have this id in their parent id field\&.
.RE
.PP
6th field: record key length
.RS 4
The length of the record key in the next field\&.
.RE
.PP
7th field: record key
.RS 4
The record key of the item\&. Use this key to restore the item\&.
.RE
.PP
8th field: content count
.RS 4
The number of items in this container, excluding other containers\&. You can use this as a hint, the restore program does not use this number\&.
.RE
.PP
9th field: last modification time
.RS 4
Unix timestamp of the date the container was last modified\&.
.RE
.PP
10th field: type of container
.RS 4
This is the type of the container\&. Eg: IPF\&.Note for a mail folder, IPF\&.Appointment for a calendar folder\&.
.RE
.PP
11th field: container name
.RS 4
The name of the container when it was backed up\&. The restored folder will have this name\&. As an exception of the separator, this field can contain a colon\&.
.RE
.PP
A message line contains 9 fields:
.PP
1st field: marker
.RS 4
M: Message marker
.RE
.PP
2nd field: unique parent id length
.RS 4
[0\-9]+: number of characters in following id
.RE
.PP
3rd field: unique parent id
.RS 4
The unique id of the message\&. This key matches the id field of the parent container\&.
.RE
.PP
4th field: record key length
.RS 4
The length of the record key in the next field\&.
.RE
.PP
5th field: record key
.RS 4
The record key of the item\&. Use this key to restore the item\&.
.RE
.PP
6th field: last modification time
.RS 4
Unix timestamp of the date the message was last modified\&.
.RE
.PP
7th field: type of message
.RS 4
This is the type of the message\&. Eg: IPM\&.Note for an email, IPM\&.Appointment for a calendar item\&.
.RE
.PP
8th field: offset in the data file
.RS 4
The restore tool needs to know where the item begins in the data file\&. This offset is the startpoint in the datafile\&.
.RE
.PP
9th field: subject of the message
.RS 4
This is a description of the message\&. You can use this to find items you want to restore\&.
.RE
.SH "OPTIONS"
.PP
The options used to backup are as follows:
.PP
\fB\-\-user\fR, \fB\-u\fR \fIusername\fR
.RS 4
Backup the store of one user\&.
.RE
.PP
\fB\-\-public\fR, \fB\-p\fR
.RS 4
Backup the public store\&. The file names will be Public\&.data\&.zbk and Public\&.index\&.zbk\&.
.RE
.PP
\fB\-\-all\fR, \fB\-a\fR
.RS 4
Backup the store of all users, including the public store\&.
.RE
.PP
\fB\-\-company\fR, \fB\-s\fR \fItenant\fR
.RS 4
Backup all users and public store of specific tenant\&.
.RE
.PP
\fB\-\-company\-public\fR, \fB\-P\fR \fIcompanyname\fR
.RS 4
Backup the public store for a specific tenant\&. The file names will be named after the tenant\&.
.RE
.PP
\fB\-\-store\fR, \fB\-i\fR \fIstoreguid\fR
.RS 4
Backup store with the specified store guid\&. This can be used to backup orphaned stores\&. Use
\fIzarafa\-admin \-\-list\-orphans\fR
to get a list of orphaned stores and their guids\&.
.RE
.PP
\fB\-\-output\fR, \fB\-o\fR \fIpath\fR
.RS 4
Store backup files in specified output directory\&.
.RE
.PP
\fB\-\-skip\-junk\fR, \fB\-J\fR
.RS 4
Do not backup the junkmail folder\&. Since this folder is likely to contain only spam, this folder is skipable\&.
.RE
.PP
\fB\-\-skip\-public\fR, \fB\-N\fR
.RS 4
Do not backup the public store\&. This can be usefull with \-a or \-s <company> options\&.
.RE
.PP
\fB\-\-host\fR, \fB\-h\fR \fIpath\fR
.RS 4
Connect to the Zarafa server through
\fIpath\fR, e\&.g\&.
\fIfile:///path/to/socket\fR\&. Default:
\fIfile:///var/run/zarafa\fR\&.
.RE
.PP
\fB\-\-config\fR, \fB\-c\fR \fIfile\fR
.RS 4
Use a configuration file\&. See the
\fBCONFIG\fR()
section for more information\&.
.sp
Default:
\fI/etc/zarafa/backup\&.cfg\fR
.RE
.PP
\fB\-\-verbose\fR, \fB\-v\fR
.RS 4
Print more ouput during the backup\&. Prints every folder with item count\&.
.RE
.SH "EXAMPLES"
.PP
Backup one user:
.PP
\fBzarafa\-backup\fR
\fB\-u\fR
\fIloginname\fR
.SH "CONFIG"
.PP
Normally, no configuration file is used or required\&. The following options can be set in the configuation file:
.PP
\fBserver_socket\fR
.RS 4
Unix socket to find the connection to the Zarafa server\&.
.sp
Default:
\fIfile:///var/run/zarafa\fR
.RE
.PP
\fBsslkey_file\fR
.RS 4
Use this file as key to logon to the server\&. This is only used when server_socket is set to an HTTPS transport\&. See the
\fBzarafa-server\fR(1)
manual page on how to setup SSL keys\&.
.sp
Default: value not set\&.
.RE
.PP
\fBsslkey_pass\fR
.RS 4
The password of the SSL key file that is set in sslkey_file\&.
.sp
Default: value not set\&.
.RE
.SH "AUTHOR"
.PP
Written by Zarafa\&.
.SH "SEE ALSO"
.PP

\fBzarafa-restore\fR(1)
