.\"     Title: zarafa-msr.cfg
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: August 2011
.\"    Manual: Zarafa user reference
.\"    Source: Zarafa 7.0
.\"
.TH "ZARAFA\-MSR\&.CFG" "5" "August 2011" "Zarafa 7.0" "Zarafa user reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
zarafa-msr.cfg \- The Mailbox Storage Relocator configuration file
.SH "SYNOPSIS"
.PP
\fBzarafa\-msr\&.cfg\fR
.SH "DESCRIPTION"
.PP
The
\fIzarafa\-msr\&.cfg\fR
is a configuration file for the Mailbox Storage Relocator\&.
\fIzarafa\-msr\&.cfg \fR
contains instructions for the software to set up the connection with the cluster and describe which user stores are to be relocated to which node\&.
.SH "FILE FORMAT"
.PP
The
\fIzarafa\-msr\&.cfg\fR
file contains of three sections:
.PP
Connection: This section contains information on how to connect to a particular node in the multi\-server cluster\&.
.PP
Servers: This section is an optional section that contains a list of server aliases\&. These aliases can be used in the Mapping section when a lot of mailboxes are relocated to the same server\&.
.PP
Mapping: This section contains the list of usernames and the destination node for their mailboxes\&. The destination node can be a full server path or an alias specified in the Servers section\&.
.SH "THE CONNECTION SECTION"
.PP
The connection setting contains the following options:
.PP
\fBserverpath\fR
.RS 4
Path to the server\&. Can be any node in the cluster\&.
.sp
Default:
\fIfile:///var/run/zarafa\fR
.RE
.PP
\fBsslkey_file\fR
.RS 4
Path the the SSL key file\&.
.sp
Default: value not set\&.
.RE
.PP
\fBsslkey_pass\fR
.RS 4
Password for the SSL key specified with sslkey_file\&.
.sp
Default: value not set\&.
.RE
.PP
\fBbidirectional\fR
.RS 4
If yes, then perform bidirectional synchronization between source and destination stores\&. If no, then only unidirectional (migration) replication is used (from source to dest)
.sp
Default: yes
.RE
.PP
\fBworkers\fR
.RS 4
Specifies the number of parallel workers to use to migrate the stores\&.
.sp
Default: 4
.RE
.PP
\fBforce_source\fR
.RS 4
Normally, the source server is only used to provide an entry point into the source cluster; If the store of the user to be migrated is on a different host, then zarafa\-msr automatically redirects to the correct source server\&. If this option is \'yes\', then no such redirection is performed\&. This is useful if the user has already been migrated to the new (destination) server, and a final MSR sync is required between the old store and the new (active) store\&. If you fail to set force_source to \'yes\' in this case, MSR will fail since source and destination store will be the same\&.
.sp
Default: no
.RE
.SH "THE SERVERS SECTION"
.PP
The servers section has no predefined options\&. Instead the format is
.PP
\fIsever_alias\fR:
\fIserver_path\fR
.PP
As many items as needed can be placed in this section\&.
.SH "THE MAPPING SECTION"
.PP
The mapping section has no predefined options\&. Instead, the format is
.PP
\fIusername\fR:
\fIdestination_node\fR
.PP
destination_node can either be the full path to the node or a reference to one of the servers from the Servers section\&. In the case of a reference, the syntax is
.PP
\fIusername\fRreplaceable>: %(\fIserver_alias\fR)s
.PP
As many items as needed can be placed in this section\&.
.PP
To relocate the public store a special name should be used for the username:
.PP
1\&. In a multi\-tenant environment, the name of the tenant for which to relocate the public store must be used\&.
.PP
2\&. In a single\-tenant environment, the special name __public__ must be used\&.
.SH "THE LOGGING SECTION"
.PP
The logging setting contains the following options:
.PP
\fBlog_file\fR
.RS 4
Path of the log file to write to\&.
.sp
Default:
\fIzarafa\-msr\&.log\fR
(in the working directory)
.RE
.SH "AUTHOR"
.PP
Written by Zarafa\&.
.SH "SEE ALSO"
.PP

\fBzarafa-msr\fR(1)
