#! /bin/sh

# Create a Zarafa Public store for the new company.

PATH=$PATH:/sbin:/usr/local/sbin:/usr/sbin

# The ZARAFA_COMPANY variable from the server will always be in UTF-8
# format.  The --utf8 option must be set before this value is used,
# since the current locale isn't necessarily UTF-8.
zarafa-admin --utf8 -s -I "${ZARAFA_COMPANY}"
