#!/bin/sh

set -e

# see if we need to notify about packaged files location change
case "$1" in
  install|upgrade)
		if dpkg --compare-versions "$2" le "6.30.2-16545"; then
			echo
			echo 'Webaccess files have been moved to /usr/share/zarafa-webaccess-mobile'
			echo 'Please read /usr/share/doc/zarafa-webaccess-mobile/NEWS.Debian.gz for more information'
			echo
		fi
		;;
esac

#DEBHELPER#

exit 0
