#! /bin/sh
#
### BEGIN INIT INFO
# Provides:          zarafa-dagent
# Required-Start:    $syslog $network $remote_fs
# Required-Stop:     $syslog $network $remote_fs
# Should-Start:      zarafa-server
# Should-Stop:       zarafa-server
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Zarafa Collaboration Platform's Delivery Agent
# Description:       The Zarafa Delivery Agent in LMTP mode can be used to
#                    run the zarafa-dagent as a daemon. The Zarafa Delivery
#                    Agent can also be used as a standalone program.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAGENT=/usr/bin/zarafa-dagent
DESC="Zarafa LMTP dagent"
NAME=`basename $DAGENT`
#QUIETDAEMON=--quiet
PIDFILE=/var/run/$NAME.pid

test -x $DAGENT || exit 0

# Include zarafa defaults if available
if [ -f /etc/default/zarafa ] ; then
	. /etc/default/zarafa
fi
if [ -z "$ZARAFA_LOCALE" ]; then
	ZARAFA_LOCALE="C"
fi

if [ -e $DAGENT_CONFIG ]; then
	DAGENT_OPTS="$DAGENT_OPTS -c $DAGENT_CONFIG"
fi

#set -e

. /lib/lsb/init-functions

case "$1" in
  start)
	if [ "$DAGENT_ENABLED" = "no" ]; then
		log_warning_msg "Zarafa DAgent LMTP daemon not enabled in /etc/default/zarafa ... not starting"
		exit 0
	fi
	log_begin_msg "Starting $DESC: $NAME"
	export LC_ALL=$ZARAFA_LOCALE
	export LANG=$ZARAFA_LOCALE
	start-stop-daemon --start $QUIETDAEMON --pidfile $PIDFILE --exec $DAGENT -- $DAGENT_OPTS
	log_end_msg $?
	unset LC_ALL LANG
	;;
  stop)
	log_begin_msg "Stopping $DESC: $NAME"
	start-stop-daemon --stop $QUIETDAEMON --pidfile $PIDFILE --retry TERM/15/KILL --exec $DAGENT
	log_end_msg $?
	;;
  restart)
	$0 stop
	$0 start
	;;
  reload|force-reload)
	log_begin_msg "Reloading $DESC: $NAME"
	start-stop-daemon --stop $QUIETDAEMON --signal HUP --pidfile $PIDFILE --exec $DAGENT
	log_end_msg $?
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	exit 1
	;;
esac

exit 0
