#! /bin/sh

# Create a Zarafa user for an already existing external user.  Create
# and initialize the user's stores.

PATH=$PATH:/sbin:/usr/local/sbin:/usr/sbin

# The ZARAFA_USER variable from the server will always be in UTF-8
# format.  The --utf8 option must be set before this value is used,
# since the current locale isn't necessarily UTF-8.
zarafa-admin --utf8 --create-store "${ZARAFA_USER}" --lang "${ZARAFA_LANG}"
