#!/usr/bin/env bash

. /etc/default/zarafa-ssm

[ -z "$ZARAFA_LICENSE_FILE" ] && ZARAFA_LICENSE_FILE=/etc/zarafa/license/base
[ -z "$ENABLED" ] && ENABLED=0

[ $ENABLED -eq 0 ] && exit 0

if [ ! -f "$ZARAFA_LICENSE_FILE" ]; then
	echo "Please correctly define ZARAFA_LICENSE_FILE in /etc/default/zarafa-ssm"
	exit 1
fi

random_sleep()
{
    RandomSleep=$1
    if [ -z "$RANDOM" ] ; then
        # A fix for shells that do not have this bash feature.
        RANDOM=$(dd if=/dev/urandom count=1 2> /dev/null | cksum | cut -c"1-5")
    fi
    TIME=$(($RANDOM % $RandomSleep))
    sleep $TIME
}

LICENSE=`cat $ZARAFA_LICENSE_FILE`
TMPD=`mktemp -d`
cd $TMPD

# basic system info
cat /proc/cpuinfo > cpuinfo
df -T -xtmpfs > df
free > free
hostname -f > hostname
uname -a > uname
cp -p /etc/SuSE-release /etc/redhat-release /etc/lsb-release /etc/debian-version . 2>/dev/null
zarafa-server -V > zarafa-version

# zarafa server stats
zarafa-stats --system &> zarafa-stats-system
zarafa-stats --users &> zarafa-stats-users
zarafa-stats --company &> zarafa-stats-company

# we really should have sar with sysstat, so copy the stat files
SAD=
if [ -d /var/log/sa ]; then
	SAD=/var/log/sa
elif [ -d /var/log/sysstat ]; then
	SAD=/var/log/sysstat
fi
if [ ! -z "$SAD" ]; then
	cp -p $SAD/sa[.0-9]* .
fi

# combine and compress files
TARFILE=$LICENSE-stats-`date +%Y%m%d`.tar.gz
tar zcpf $TARFILE --remove-files *

random_sleep 600
wget -q -O /dev/null --post-file "$TARFILE" https://report.zarafa.com/monitor/?filename=$TARFILE

# cleanup
rm $TARFILE
rmdir $TMPD
