#! /bin/sh

# Zarafa script that is executed whenever a new group is created in the
# external user source, such as an Active Directory tree or
# /etc/passwd.

# This script executes all scripts in /etc/zarafa/userscripts/creategroup.d
# using find.  The environment variable ZARAFA_GROUP is set, but
# beware that this string can contain any characters, so take heed to
# correct quoting.

if [ -f ${prefix}/etc/sysconfig/zarafa ]; then
  . ${prefix}/etc/sysconfig/zarafa
elif [ -f ${prefix}/etc/default/zarafa ]; then
  . ${prefix}/etc/default/zarafa
fi

ZARAFA_GROUP_SCRIPTS=/etc/zarafa/userscripts/creategroup.d
. /etc/zarafa/userscripts/groups_common.sh
